### ISSUE TITLE
Make Monoclonal Antibodies (NAbMAb) data available

### ISSUE THREAD

**Issue by juyeongkim** [ropensci/DataSpaceR#14]
App workflow:
- Navigate to [MAb Grid](https://dataspace.cavd.org/cds/CAVD/app.view#mabgrid)
- Select "MAb/Mixture"
- Click "Export CSV" or "Export Excel" to download MAb data

Potential workflow with `DataSpaceR`:

```R
devtools::install_github("CAVDDataSpace/DataSpaceR", ref = "fb_mAb")

# connect to DataSpace
library(DataSpaceR)
con <- connectDS()

# explore mAb Grid and decide on which MAb to pull data
con$mAbGrid

# filter mAb grid by mixture name, donor species, viruses, isotype, hxb2 location, viruses, clades, tiers, curve IC50), or studies
con$filterMabGrid(using = "isotype", value = "IgG")
con$filterMabGrid(using = "donor_species", value = "llama")

# get mAb dataset of mAb fixtures from filtered mAb grid
myMab <- con$getMab()

# explore mAb object (mimic the contents of excel file or csv files)
myMab$mabs
myMab$nabMab
myMab$studies
myMab$assays
myMab$metadata
myMab$variableDefinitions
myMab$studyAndMabs
```

- [x] Implement `mAbGrid`
- [x] Implement `filterMAb()` and `clearMAbfilter()`
- [x] Implement `DataSpaceMAb` class
- [x] Implement `getMAb()`
- [ ] Write tests
- [ ] Document
- [ ] Write a vignette

https://github.com/LabKey/cds/blob/bdc9346651346029f8d623e99617f2cc53533450/webapp/Connector/src/utility/MabQuery.js#L493

**Comment by jmtaylor-fhcrc** [comment]
Things I think will be important:

* Users should be able to get unique lists of filterable values.
* The `value` argument should be able to accept multi element vectors. So, c("llama", "human").

It seems like `con$mAbGrid` will give the users an object to get those unique values. I think it would be straight forward to set up `con$filterMAb` to accept unique subsets from `con$mAbGrid`.

Looks great!

**Comment by juyeongkim** [comment]
- Yeah, that's a good idea.
- That's already implemented. (2c7ef218d07377a3142b676cb55013da9d5d316a)
- What do you mean by unique values? Also, `con$filterMAb` is set up to subset `mAbGrid` with the given filter, not the other way around.

Thanks!

**Comment by jmtaylor-fhcrc** [comment]
```

**Comment by jmtaylor-fhcrc** [comment]
This is what I had in mind. I suspect this was already your intention.

```
iso <- unique(con$mAbGrid$isotype)

## What are my options for isotype?
iso

## I want evertything but "IgG"
filtIso <- iso[iso != "IgG"] 

con$filterMAb(using = "isoType", value = filtIso)
```

**Comment by juyeongkim** [comment]
yeah exactly
